-- ==================== INSERT CREDENTIALS ====================
--INSERT INTO CREDENTIALS (CREDENTIALS_ID, EMAIL, PASSWORD_HASH, PASSWORD_SALT)
--VALUES (SEQ_CREDENTIALS_ID.NEXTVAL, 'esoma.koality@mailinator.com', '7B5FB660184AE97DC84E9F30953D4BB07B5AA17A06D149F9DB7E86FCF4DD8F88', 'ab12');
--INSERT INTO CREDENTIALS (CREDENTIALS_ID, EMAIL, PASSWORD_HASH, PASSWORD_SALT)
--VALUES (SEQ_CREDENTIALS_ID.NEXTVAL, 'sjie.koality@mailinator.com', '586CB5F074C60573988DBB94B6643C6FE2A8186A7683D8A14CF9F40F4C23B30A', '4dF6');
--INSERT INTO CREDENTIALS (CREDENTIALS_ID, EMAIL, PASSWORD_HASH, PASSWORD_SALT)
--VALUES (SEQ_CREDENTIALS_ID.NEXTVAL, 'jseals.koality@mailinator.com', '63D92F6D8E804306CAD6BED4D58DCAF34C7D674022233094D1BD6C6B1E70D5BA', 'E31F');

-- ==================== INSERT KOALIBEE ====================
--INSERT INTO KOALIBEE (KOALIBEE_ID, FIRST_NAME, LAST_NAME, EMAIL, ETA_BALANCE, AVATAR, AVATAR_TYPE, CREDENTIALS_ID)
--VALUES (SEQ_KOALIBEE_ID.NEXTVAL, 'Eddy', 'Soma', 'esoma.koality@mailinator.com', 1000, NULL, 'JPG', 1);
--INSERT INTO KOALIBEE (KOALIBEE_ID, FIRST_NAME, LAST_NAME, EMAIL, ETA_BALANCE, AVATAR, AVATAR_TYPE, CREDENTIALS_ID)
--VALUES (SEQ_KOALIBEE_ID.NEXTVAL, 'Sang', 'Jie', 'sjie.koality@mailinator.com', 550, NULL, 'JPG', 2);
--INSERT INTO KOALIBEE (KOALIBEE_ID, FIRST_NAME, LAST_NAME, EMAIL, ETA_BALANCE, AVATAR, AVATAR_TYPE, CREDENTIALS_ID)
--VALUES (SEQ_KOALIBEE_ID.NEXTVAL, 'Julie', 'Seals', 'jseals.koality@mailinator.com', 600, NULL, 'PNG', 3);

COMMIT;