-- ==================== DROP SEQUENCES ====================
--DROP SEQUENCE SEQ_GENRE_ID;
--DROP SEQUENCE SEQ_KOALIBEE_ID;
--DROP SEQUENCE SEQ_CREDENTIALS_ID;
--DROP SEQUENCE SEQ_MOMENT_ID;
--DROP SEQUENCE SEQ_ALBUM_ID;
--DROP SEQUENCE SEQ_TRACK_ID;
--DROP SEQUENCE SEQ_REVIEW_ID;

-- ==================== DROP TABLES ====================
--DROP TABLE KOALIBEE_ALBUM;
--DROP TABLE REVIEW;
--DROP TABLE MOMENT;
--DROP TABLE TRACK;
--DROP TABLE CREDENTIALS;
--DROP TABLE ALBUM;
--DROP TABLE KOALIBEE;
--DROP TABLE GENRE;

-- ==================== CREATE TABLES ====================
CREATE TABLE GENRE (
	GENRE_ID INT PRIMARY KEY,
	GENRE_NAME VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE KOALIBEE (
	KOALIBEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR2(30) NOT NULL,
	LAST_NAME VARCHAR2(30) NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	ETA_BALANCE INT NOT NULL,
	AVATAR BLOB,
	AVATAR_TYPE VARCHAR2(4)
);

CREATE TABLE CREDENTIALS (
	CREDENTIALS_ID INT PRIMARY KEY,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PASSWORD_HASH VARCHAR2(64) NOT NULL,
	PASSWORD_SALT VARCHAR2(4) NOT NULL,
	KOALIBEE_ID INT NOT NULL
);

CREATE TABLE MOMENT (
	MOMENT_ID INT PRIMARY KEY,
	POST_DATE DATE NOT NULL,
	POST_COMMENT VARCHAR2(2000),
	KOALIBEE_ID INT NOT NULL,
	UNIQUE (KOALIBEE_ID, POST_DATE)
);

CREATE TABLE ALBUM (
	ALBUM_ID INT PRIMARY KEY,
	ALBUM_NAME VARCHAR2(100) NOT NULL,
	ARTIST VARCHAR2(100),
	ARTWORK BLOB,
	ARTWORK_TYPE VARCHAR2(4),
	ETA_PRICE INT NOT NULL,
	IS_PROMOTED VARCHAR2(1) NOT NULL,
	IS_PUBLISHED VARCHAR2(1) NOT NULL,
	GENRE_ID INT NOT NULL,
	KOALIBEE_ID INT NOT NULL
);

CREATE TABLE TRACK (
	TRACK_ID INT PRIMARY KEY,
	TRACK_NAME VARCHAR2(100) NOT NULL,
	COMPOSER VARCHAR2(100),
	TRACK_LENGTH INT NOT NULL,
	AUDIO BLOB,
	AUDIO_TYPE VARCHAR2(4),
	IS_DEMO VARCHAR2(1) NOT NULL,
	ALBUM_ID INT NOT NULL
);

CREATE TABLE REVIEW (
	REVIEW_ID INT PRIMARY KEY,
	RATING INT NOT NULL,
	REVIEW_COMMENT VARCHAR2(2000),
	ALBUM_ID INT NOT NULL,
	KOALIBEE_ID INT NOT NULL,
	UNIQUE (KOALIBEE_ID, ALBUM_ID)
);

CREATE TABLE KOALIBEE_ALBUM (
	KOALIBEE_ID INT NOT NULL,
	ALBUM_ID INT NOT NULL,
	PRIMARY KEY (KOALIBEE_ID, ALBUM_ID)
);

-- ==================== CREATE SEQUENCES ====================
CREATE SEQUENCE SEQ_GENRE_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_KOALIBEE_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_CREDENTIALS_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_MOMENT_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_ALBUM_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_TRACK_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- ==================== CREATE CONSTRAINTS ====================
ALTER TABLE CREDENTIALS
ADD CONSTRAINT FK_KOALIBEE_ID_CREDENTIALS
FOREIGN KEY (KOALIBEE_ID) REFERENCES KOALIBEE(KOALIBEE_ID)
ON DELETE CASCADE;

ALTER TABLE MOMENT
ADD CONSTRAINT FK_KOALIBEE_ID_MOMENT
FOREIGN KEY (KOALIBEE_ID) REFERENCES KOALIBEE(KOALIBEE_ID)
ON DELETE CASCADE;

ALTER TABLE ALBUM
ADD CONSTRAINT FK_GENRE_ID_ALBUM
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
ON DELETE CASCADE;

ALTER TABLE ALBUM
ADD CONSTRAINT FK_KOALIBEE_ID_ALBUM
FOREIGN KEY (KOALIBEE_ID) REFERENCES KOALIBEE(KOALIBEE_ID)
ON DELETE CASCADE;

ALTER TABLE TRACK
ADD CONSTRAINT FK_ALBUM_ID_TRACK
FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID)
ON DELETE CASCADE;

ALTER TABLE REVIEW
ADD CONSTRAINT FK_KOALIBEE_ID_REVIEW
FOREIGN KEY (KOALIBEE_ID) REFERENCES KOALIBEE(KOALIBEE_ID)
ON DELETE CASCADE;

ALTER TABLE REVIEW
ADD CONSTRAINT FK_ALBUM_ID_REVIEW
FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID)
ON DELETE CASCADE;

ALTER TABLE KOALIBEE_ALBUM
ADD CONSTRAINT FK_KOALIBEE_ID_KA
FOREIGN KEY (KOALIBEE_ID) REFERENCES KOALIBEE(KOALIBEE_ID)
ON DELETE CASCADE;

ALTER TABLE KOALIBEE_ALBUM
ADD CONSTRAINT FK_ALBUM_ID_KA
FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID)
ON DELETE CASCADE;