-- ==================== DELETE ALL RECORDS ====================
DELETE FROM KOALIBEE_ALBUM;
DELETE FROM REVIEW;
DELETE FROM MOMENT;
DELETE FROM TRACK;
DELETE FROM ALBUM;
DELETE FROM KOALIBEE;
DELETE FROM CREDENTIALS;
DELETE FROM GENRE;

COMMIT;

-- ==================== DROP SEQUENCES ====================
DROP SEQUENCE SEQ_GENRE_ID;
DROP SEQUENCE SEQ_KOALIBEE_ID;
DROP SEQUENCE SEQ_CREDENTIALS_ID;
DROP SEQUENCE SEQ_MOMENT_ID;
DROP SEQUENCE SEQ_ALBUM_ID;
DROP SEQUENCE SEQ_TRACK_ID;
DROP SEQUENCE SEQ_REVIEW_ID;

-- ==================== RECREATE SEQUENCES ====================
CREATE SEQUENCE SEQ_GENRE_ID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE SEQ_KOALIBEE_ID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE SEQ_CREDENTIALS_ID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE SEQ_MOMENT_ID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE SEQ_ALBUM_ID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE SEQ_TRACK_ID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- ==================== TEST INSERT CREDENTIALS ====================
INSERT INTO CREDENTIALS (CREDENTIALS_ID, EMAIL, PASSWORD_HASH, PASSWORD_SALT)
VALUES (NEXTVAL('SEQ_CREDENTIALS_ID'), 'good.user@koalibee.com', 'CEB11D2AB244A259D27007E69C18F5AFD287F8D3AB4E1DB916C3F70E83BC8146', 'rfE4');
INSERT INTO CREDENTIALS (CREDENTIALS_ID, EMAIL, PASSWORD_HASH, PASSWORD_SALT)
VALUES (NEXTVAL('SEQ_CREDENTIALS_ID'), 'my.music@koalibee.com', '0444B4A904C26E19C5E5951D44359068E2E001339FE8193F91787EE36E182CCE', 'C58u');
INSERT INTO CREDENTIALS (CREDENTIALS_ID, EMAIL, PASSWORD_HASH, PASSWORD_SALT)
VALUES (NEXTVAL('SEQ_CREDENTIALS_ID'), 'esoma.aws@jenkins.com', '26BEF48AD5C232CE7E50A3106461188617AC7AB514479F26AD20F00FD99CAD81', 'f5vg');

-- ==================== TEST INSERT KOALIBEE ====================
INSERT INTO KOALIBEE (KOALIBEE_ID, FIRST_NAME, LAST_NAME, EMAIL, ETA_BALANCE, AVATAR, AVATAR_TYPE, CREDENTIALS_ID)
VALUES (NEXTVAL('SEQ_KOALIBEE_ID'), 'John', 'Smith', 'good.user@koalibee.com', 0, NULL, NULL, 1);
INSERT INTO KOALIBEE (KOALIBEE_ID, FIRST_NAME, LAST_NAME, EMAIL, ETA_BALANCE, AVATAR, AVATAR_TYPE, CREDENTIALS_ID)
VALUES (NEXTVAL('SEQ_KOALIBEE_ID'), 'Julie', 'Seals', 'my.music@koalibee.com', 0, '72616e646f6d6279746573', 'JPG', 2);
INSERT INTO KOALIBEE (KOALIBEE_ID, FIRST_NAME, LAST_NAME, EMAIL, ETA_BALANCE, AVATAR, AVATAR_TYPE, CREDENTIALS_ID)
VALUES (NEXTVAL('SEQ_KOALIBEE_ID'), 'Eddy', 'Soma', 'esoma.aws@jenkins.com', 50, NULL, NULL, 3);

-- ==================== TEST INSERT MOMENT ====================
INSERT INTO MOMENT (MOMENT_ID, POST_DATE, POST_COMMENT, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_MOMENT_ID'), PARSEDATETIME('2018-10-09', 'yyyy-MM-dd'), 'Jesus!', 1);
INSERT INTO MOMENT (MOMENT_ID, POST_DATE, POST_COMMENT, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_MOMENT_ID'), PARSEDATETIME('2019-01-16', 'yyyy-MM-dd'), 'I love tianshi dongman', 3);
INSERT INTO MOMENT (MOMENT_ID, POST_DATE, POST_COMMENT, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_MOMENT_ID'), PARSEDATETIME('2017-06-05', 'yyyy-MM-dd'), 'Nothing I want to say', 2);
INSERT INTO MOMENT (MOMENT_ID, POST_DATE, POST_COMMENT, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_MOMENT_ID'), PARSEDATETIME('2019-02-24', 'yyyy-MM-dd'), 'man, JavaScript is garbage', 2);
INSERT INTO MOMENT (MOMENT_ID, POST_DATE, POST_COMMENT, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_MOMENT_ID'), PARSEDATETIME('2018-11-30', 'yyyy-MM-dd'), 'Angular is way better than React.', 1);

-- ==================== TEST INSERT GENRE ====================
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Classical');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Blues');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Pop');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Rapping');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Country');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Folk');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Jazz');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (NEXTVAL('SEQ_GENRE_ID'), 'Disco');

-- ==================== TEST INSERT ALBUM ====================
INSERT INTO ALBUM (ALBUM_ID, ALBUM_NAME, ARTIST, ARTWORK, ARTWORK_TYPE, ETA_PRICE, IS_PROMOTED, IS_PUBLISHED, GENRE_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_ALBUM_ID'), 'Etudes Liszt', 'Ovchinnikov', NULL, 'PNG', 90, 'F', 'F', 1, 3);
INSERT INTO ALBUM (ALBUM_ID, ALBUM_NAME, ARTIST, ARTWORK, ARTWORK_TYPE, ETA_PRICE, IS_PROMOTED, IS_PUBLISHED, GENRE_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_ALBUM_ID'), 'New Album', 'Unknown', NULL, 'JPG', 0, 'F', 'F', 6, 2);
INSERT INTO ALBUM (ALBUM_ID, ALBUM_NAME, ARTIST, ARTWORK, ARTWORK_TYPE, ETA_PRICE, IS_PROMOTED, IS_PUBLISHED, GENRE_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_ALBUM_ID'), 'My Album', 'Esoma', NULL, NULL, 40, 'F', 'F', 1, 3);
INSERT INTO ALBUM (ALBUM_ID, ALBUM_NAME, ARTIST, ARTWORK, ARTWORK_TYPE, ETA_PRICE, IS_PROMOTED, IS_PUBLISHED, GENRE_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_ALBUM_ID'), 'Hehe', 'Kanye West', NULL, NULL, 50, 'F', 'F', 4, 1);
INSERT INTO ALBUM (ALBUM_ID, ALBUM_NAME, ARTIST, ARTWORK, ARTWORK_TYPE, ETA_PRICE, IS_PROMOTED, IS_PUBLISHED, GENRE_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_ALBUM_ID'), 'Fortissimo', 'Nanjo', '4a6176612c204153502e4e45542c20432b2b2c20466f727472616e20657463', 'PNG', 100, 'F', 'T', 3, 3);
INSERT INTO ALBUM (ALBUM_ID, ALBUM_NAME, ARTIST, ARTWORK, ARTWORK_TYPE, ETA_PRICE, IS_PROMOTED, IS_PUBLISHED, GENRE_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_ALBUM_ID'), 'More Jazz', 'The Hazz Man', NULL, 'BMP', 0, 'F', 'F', 7, 3);

-- ==================== TEST INSERT TRACK ====================
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Mazeppa', 'Liszt', 420, NULL, 'OGG', 'F', 1);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Chasse-neige', 'Liszt', 300, NULL, 'MP3', 'F', 1);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'My Day', 'Bear', 550, NULL, 'OGG', 'T', 2);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Wonderful', 'Pear', 10, NULL, 'OGG', 'F', 2);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Vox', 'Know', 90, NULL, 'OGG', 'T', 3);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'I am a Genius', 'Eddy', 220, NULL, 'OGG', 'F', 3);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Sunrise', 'Unknown', 350, NULL, 'MP3', 'F', 3);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Baba', 'West', 580, NULL, 'MP3', 'F', 4);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Only My Railgun', 'ZhaoWu', 600, NULL, 'MP3', 'F', 5);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Ultimate Crisis', 'ZhaoWu', 300, '706f696e7420323020696e206865782c20333220696e20646563696d616c2e', 'MP3', 'F', 5);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Sword of Origin', 'ZhaoWu', 250, NULL, 'OGG', 'F', 5);
INSERT INTO TRACK (TRACK_ID, TRACK_NAME, COMPOSER, TRACK_LENGTH, AUDIO, AUDIO_TYPE, IS_DEMO, ALBUM_ID)
VALUES (NEXTVAL('SEQ_TRACK_ID'), 'Jasmine', 'Jazzman', 1500, NULL, 'MP3', 'T', 6);

-- ==================== TEST INSERT REVIEW ====================
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'Just amazing!', 1, 1);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'Piece of poo', 5, 2);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'No nono', 6, 1);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'Awesome', 2, 3);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'WTFOMG Psyche', 1, 3);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'My favorite', 4, 2);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'what is this??', 6, 2);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'This is my vege', 2, 1);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'Never want to listen to this ever', 5, 3);
INSERT INTO REVIEW (REVIEW_ID, RATING, REVIEW_COMMENT, ALBUM_ID, KOALIBEE_ID)
VALUES (NEXTVAL('SEQ_REVIEW_ID'), 5, 'give my eta back.', 4, 1);

COMMIT;
